require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false